let @a = "/^class AstIabstract v0"
let @b = "1G/void dump$%zzAvoid gen(String successor);String get linkage => name == \"f0\" ? \"external\" : \"internal\";void forward(String to) {print(\"define $linkage i32 @$name(i8* %s) {\");print(\"  %result = call i32 @${to}(i8* %s)\");print(\"  ret i32 %result\");print(\"}\");}V7k"
let @c = "/class Literal$%Ovoid gen(String successor) {print(\"define $linkage i32 @$name(i8* %s) {\");// char c = *sprint(\"  %c = load i8, i8* %s, align 1\");// bool comparison = c == ascii_code_of_literalprint(\"  %comparison = icmp eq i8 %c, ${str.codeUnitAt(0)}\");// if comparison goto matched else goto got_result;print(\"  br i1 %comparison, label %matched, label %got_result\");print(\"matched:\");// char* next = s + 1;print(\"  %next = getelementptr i8, i8* %s, i64 1\");// int succ_result = f42(next);print(\"  %succ_result = call i32 @$successor(i8* %next)\");// goto got_result;print(\"  br label %got_result\");print(\"got_result:\");// int result = phi(succ_result, 0);print(\"  %result = phi i32 [ %succ_result, %matched ], [ 0, %0 ]\");// return resultprint(\"  ret i32 %result\");print(\"}\");}v%0"
let @d = "/class Disj$%kAvoid gen(String succ) {print('define $linkage i32 @$name(i8* %s) {');print('  %left = call i32 @${l.name}(i8* %s)');print('  %comparison = icmp eq i32 %left, 0');print('  br i1 %comparison, label %left_failed, label %got_result');print('left_failed:');print('  %right = call i32 @${r.name}(i8* %s)');print('  br label %got_result');print('got_result:');print('  %result = phi i32 [ %right, %left_failed ], [ 1, %0 ]');print('  ret i32 %result');print('}');l.gen(succ);r.gen(succ);}"
let @e = "/class Empty$zz%Ovoid gen(String succ) {forward(succ);}v%0"
let @f = "/class Alter$zz%Ovoid gen(String succ) {forward(l.name);l.gen(r.name);r.gen(succ);}v%0"
let @g = "/main$%cnmain(List<String> args) {Parser parser = new Parser(\"a(b|c)?d\");Ast ast = parser.parse();if (args[0] == \"dot\") {print(\"Digraph G {\");ast.dump();print(\"}\");} else {print(\"declare i32 @match(i8* %s)\");ast.gen(\"match\");}jv%0"


